apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-gbreana-demo-app-in-gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc:8181/root/iot-gbreana-demo-app.git
    targetRevision: main
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
