global:
  hosts:
    domain: student.42.fr
  edition: ce
  ingress:
    configureCertmanager: false
  kas:
    enabled: false
  pages:
    enabled: false

certmanager-issuer:
  email: gbreana@student.42.fr

certmanager:
  startupapicheck:
    enabled: false

prometheus:
  install: false

gitlab-runner:
  install: false

gitlab:
  webservice:
    replicaCount: 1
  sidekiq:
    replicaCount: 1
  mailroom:
    enabled: false
  spamcheck:
    enabled: false
