Vagrant.configure("2") do |config|
    config.vm.box = "boxomatic/debian-13"

    config.vm.define "gbreanaS" do |server|
        server.vm.hostname = "gbreanaS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |v|
            v.memory=2048
            v.cpus=2
            v.customize ["modifyvm", :id, "--cpuexecutioncap", "60"]
            v.name="gbreanaS"
        end
        server.vm.provision "shell", path: "scripts/server.sh"
    end
end
