Vagrant.configure("2") do |config|
    config.vm.box = "boxomatic/debian-13"

    config.vm.define "gbreanaS" do |server|
        server.vm.hostname = "gbreanaS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provider "virtualbox" do |v|
            v.memory=2048
            v.cpus=2
            v.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
            v.name="gbreanaS"
        end
        server.vm.provision "shell", path: "scripts/server.sh"
    end
    config.vm.define "gbreanaSW" do |worker|
        worker.vm.hostname = "gbreanaSW"
        worker.vm.network "private_network", ip: "192.168.56.111"
        worker.vm.provider "virtualbox" do |v|
            v.memory=1024
            v.cpus=1
            v.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
            v.name="gbreanaSW"
        end
        worker.vm.provision "shell", path: "scripts/worker.sh"
    end
end
